analyzer:
  errors:
    todo: ignore
    missing_return: ignore
    missing_enum_constant_in_switch: ignore
    body_might_complete_normally_nullable: ignore
language:
    strict-casts: true
    strict-raw-types: true
linter:
  rules:
    - annotate_overrides
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_relative_lib_imports
    #- avoid_return_types_on_setters
    #- avoid_returning_null
    #- avoid_slow_async_io
    - avoid_types_as_parameter_names
    - avoid_unused_constructor_parameters
    - camel_case_types
    - cancel_subscriptions
    #- close_sinks
    - collection_methods_unrelated_type
    # - constant_identifier_names
    - hash_and_equals
    - no_duplicate_case_values
    #- non_constant_identifier_names
    - null_check_on_nullable_type_parameter
    - prefer_const_constructors_in_immutables
    #- prefer_final_fields
    #- unnecessary_new
    #- type_init_formals
    - unnecessary_await_in_return
    #- unnecessary_brace_in_string_interps
    - unnecessary_late
    - test_types_in_equals
    - unrelated_type_equality_checks
    - valid_regexps
