name: y_crdt
description: A starting point for Dart libraries or applications.
version: 0.0.2
# homepage: https://www.example.com

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  fixnum: any
  uuid: any

dev_dependencies:
  lint: any
  test: any
  dart_quill_delta: any
