name: y_crdt
description: A starting point for Dart libraries or applications.
version: 0.0.2
# homepage: https://www.example.com

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  fixnum: ^1.0.0
  uuid: ^3.0.0

dev_dependencies:
  lint: ^1.0.0
  test: ^1.16.0-nullsafety.12
